### ISSUE TITLE
easier ability to read all headers

### ISSUE THREAD

**Issue by GlenDC** [LorenzoLeonardo/curl-http-client#16]
Currently only content-type header is read. That said, this library has made it a lot easier for me to integrate libcurl into my project so thanks a lot for your efforts.

That said, if it fits within the scope of your project, would probably be useful if one can access _all_ headers from a response. For now this is how I've done it:

1. enable `show_headers(true)`
2. search in the bytes of the body (payload) for the response (e.g. making sure to skip the proxy CONNECT headers if these are also there)
3. use `httparse` to parse the response

And as such I have access to all headers.

This is however pretty fragile and works only because I am for now only using it on one website and only for HTTP/1.1

What do you think. In the `Easy` client there is a way to enable a callback to get all headers. `Easy2` doesn't seem to have this.
Does supporting this fit within your project or is this out of scope?

Either way, thanks a lot!

**Comment by LorenzoLeonardo** [comment]
This crate would only use Easy2 since it is easier to handle when implementing async operations than Easy. I am open for a pull request to improve this crate. I am still learning about https://github.com/alexcrichton/curl-rust. We can ask them if they can add it for Easy2.

**Comment by LorenzoLeonardo** [comment]
We could also ask the creators of curl-rust to have an interface to get all header responses. As of the moment, it seems we can access it one by one.

**Comment by GlenDC** [comment]
Ok. Added a issue for starting a discussion there: https://github.com/alexcrichton/curl-rust/issues/544

**Comment by GlenDC** [comment]
Closing this issue as is. Seems I can just implement my own collector and then all is good, as explained here: https://github.com/alexcrichton/curl-rust/issues/544#issuecomment-1913358372
