### ISSUE TITLE
consider to use tracing instead of `eprintln`

### ISSUE THREAD

**Issue by GlenDC** [LorenzoLeonardo/curl-http-client#17]
Hi!

For now it seems you use `eprintln` to print stuff.
Would it be possible to instead use something more standard such as `tracing`?
This way one can choose what to do with these logs instead of them always showing up

**Comment by LorenzoLeonardo** [comment]
Hi @GlenDC thank you for the suggestion. I am open for a PR. How about we use https://docs.rs/fern/latest/fern/ ?

**Comment by GlenDC** [comment]
All good for me. As far as I can see it uses ‘log’ which can be handled by any tracing environment out of the box if I’m not wrong. So yeah if that’s your preference then I respect that with pleasure.

that said usually for libraries one keeps the logging simple (eg use log or tracing) and leave it to to the consumers to actually do stuff like couloring the logs. But again you tell me, you decide and I can open a PR  tonight with great pleasure.

**Comment by GlenDC** [comment]
Opened 2 PR's about this:

* https://github.com/LorenzoLeonardo/curl-http-client/pull/19
* https://github.com/LorenzoLeonardo/async-curl/pull/18
