### ISSUE TITLE
is 'Warning! The receiver has been dropped. Ok' normal or do I do something wrong?

### ISSUE THREAD

**Issue by GlenDC** [LorenzoLeonardo/curl-http-client#18]
I receive quiet often `Warning! The receiver has been dropped. Ok` (most of the times not, but sufficient times that they are easy to see in my logs). Is this ok? Or do I do something wrong?

For now I was following the examples (get + concurrent). Do I perhaps need to close / cleanup something more then what those examples show? Or is this just to be expected? if so , it might be better to have these as verbose/debug logs instead of warnings?

**Comment by LorenzoLeonardo** [comment]
Ahh I am just adding it just case the receiving channel was dropped for information only. We can use fern logger so that it won't be noisy. I have this actor model crate to be able to have async implementation for curl https://github.com/LorenzoLeonardo/async-curl/blob/master/src/actor.rs

**Comment by GlenDC** [comment]
Yes, that is the actor I use.

Here you can see in extracted code how I more or less use your two libraries: https://github.com/plabayo/rama/issues/48

so not sure why this happens a lot, but given I do await for the response I think it should be ok. Maybe it’s because these are http/1.1 keep alive connections and the server sends another response for w/e reason, but in the case I would suggest we demote this to a debug log.

**Comment by GlenDC** [comment]
Ok opened a PR for it: https://github.com/LorenzoLeonardo/async-curl/pull/18

**Comment by GlenDC** [comment]
Completed with the above merged PR.
